//USER ACTIONS
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const GET_ACTIVE_USER_SUCCESS = 'GET_ACTIVE_USER_SUCCESS';
export const GET_ACTIVE_USER_ERROR = 'GET_ACTIVE_USER_ERROR';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_ERROR = 'SEARCH_USERS_ERROR';
export const UPLOAD_PROFILE_PIC_SUCCESS = 'UPLOAD_PROFILE_PIC_SUCCESS';
export const UPLOAD_PROFILE_PIC_ERROR = 'UPLOAD_PROFILE_PIC_ERROR';
export const UPLOAD_BG_PICTURE_SUCCESS = 'UPLOAD_BG_PICTURE_SUCCESS';
export const UPLOAD_BG_PICTURE_ERROR = 'UPLOAD_BG_PICTURE_ERROR';
export const UPDATE_USERNAME_SUCCESS = 'UPDATE_USERNAME_SUCCESS';
export const UPDATE_USERNAME_ERROR = 'UPDATE_USERNAME_ERROR';
export const LOAD_START_USERS = 'LOAD_START_USERS';
export const LOAD_END_USERS = 'LOAD_END_USERS';
export const RESET_REDIRECT_PATH_USERS = 'RESET_REDIRECT_PATH_USERS';

//COURSES ACTIONS
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_ERROR = 'CREATE_COURSE_ERROR';
export const GET_COURSE_BY_ID_SUCCESS = 'GET_COURSE_BY_ID_SUCCESS';
export const GET_COURSE_BY_ID_ERROR = 'GET_COURSE_BY_ID_ERROR';
export const LOAD_START_COURSES = 'LOAD_START_COURSES';
export const LOAD_END_COURSES = 'LOAD_END_COURSES';
export const RESET_REDIRECT_PATH_COURSES = 'RESET_REDIRECT_PATH_COURSES';
export const EDIT_COURSE_SUCCESS = 'EDIT_COURSE_SUCCESS';
export const EDIT_COURSE_ERROR = 'EDIT_COURSE_ERROR';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_ERROR = 'DELETE_COURSE_ERROR';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_ERROR = 'GET_COURSES_ERROR';

//LECTURE ACTIONS
export const ADD_LECTURE_SUCCESS = 'ADD_LECTURE_SUCCESS';
export const ADD_LECTURE_ERROR = 'ADD_LECTURE_ERROR';
export const EDIT_LECTURE_SUCCESS = 'EDIT_LECTURE_SUCCESS';
export const EDIT_LECTURE_ERROR = 'EDIT_LECTURE_ERROR';
export const DELETE_LECTURE_SUCCESS = 'DELETE_LECTURE_SUCCESS';
export const DELETE_LECTURE_ERROR = 'DELETE_LECTURE_ERROR';
export const GET_LECTURE_BY_ID_SUCCESS = 'GET_LECTURE_BY_ID_SUCCESS';
export const GET_LECTURE_BY_ID_ERROR = 'GET_LECTURE_BY_ID_ERROR';
export const GET_LECTURES_SUCCESS = 'GET_LECTURES_SUCCESS';
export const GET_LECTURES_ERROR = 'GET_LECTURES_ERROR';
export const LOAD_START_LECT = 'LOAD_START_LECT';
export const LOAD_END_LECT = 'LOAD_END_LECT';
export const RESET_REDIRECT_PATH_LECT = 'RESET_REDIRECT_PATH_LECT';
export const UPLOAD_VIDEO_SUCCESS = 'UPLOAD_VIDEO_SUCCESS';
export const UPLOAD_VIDEO_ERROR = 'UPLOAD_VIDEO_ERROR';